server {
    listen 80;
    server_name localhost;

    location /api/ {
        proxy_pass http://backend:3000/;
        proxy_set_header Host $host;
    }

    location /adminer {
        proxy_pass http://adminer:8080;
        proxy_set_header Host $host;
    }
}
